<?php

use Krystal\Form\Element;

?>

<form class="card card-body" autocomplete="off">
    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Items per page to show'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::number('config[per_page_count]', $config->getPerPageCount(), ['class' => 'form-control', 'min' => '1', 'required' => true]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
            <div class="form-text"><?= $this->translate('How many results do you want to display on site per page?'); ?></div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Maximal description length'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::number('config[max_description_length]', $config->getMaxDescriptionLength(), ['class' => 'form-control', 'min' => '10']); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
            <div class="form-text"><?= $this->translate('Maximal length for description text when displaying results on site'); ?></div>
        </div>
    </div>

    <div class="actions">
        <button data-button="save" data-url="<?= $this->url('Search:Admin:Config@saveAction'); ?>" class="btn btn-primary"><i class="bi bi-save"></i> <?= $this->translate('Save'); ?></button>
        <button data-button="cancel" data-url="/admin" class="btn btn-secondary"><i class="bi bi-folder2-open"></i> <?= $this->translate('Cancel'); ?></button>
    </div>
</form>